---
title: "Project 2"
author: "James Weaver"
date: "2023-12-22"
output:
  pdf_document: default
  html_document: default
---

```{r}

```


```{r}
# import libraries
## install.packages("naniar")
## install.packages("ggpubr")
## install.packages("dplyr")
## install.packages("ggplot2")
## install.packages("tibble")
## install.packages("tidyr")
## install.packages("GGally")
## install.packages("corrplot")
## install.packages("caret")
```


```{r}
# upload libraries
#library(dplyr)
#library(ggplot2)
#library(tibble)
#library(tidyr)
#library(ggpubr)
#library(naniar)
#library(GGally)
#library(corrplot)
# library(caret)
```



```{r}
# upload data
data <- read.csv("CaseStudy2-data.csv")
head(data)
```
```{r}
str(data)
```

```{r}
# Change all char variables to factors
library(tidyverse)
data <- data %>%
  mutate_if(is.character, as.factor)

str(data)
```





```{r}
set.seed(314)

obv <- nrow(data) # number of obervations
shuff_obv <- sample(obv) # shuffled obv index
data_shuff <- data[shuff_obv,] # shuffled data
split <- round(obv*0.80)

train <- data_shuff[1:split,] #  train
test <- data_shuff[(split+1):obv,] # test

table(train$Attrition)
```

Classification 

```{r}

str(train)


```
Checking For Multicollinairity

```{r,  fig.width=12, fig.height=12}
library(corrplot)

num_train <- train %>% 
  select_if(~!is.character(.x) & !is.factor(.x))

M <- cor(num_train)
corrplot(M, method="number",col = rainbow(12), tl.cex = 0.4)
```
Eliminating High Corrlated variables

```{r}
train_top6 <- train %>%
              select(JobSatisfaction,YearsAtCompany,Age,WorkLifeBalance,MonthlyIncome,JobRole,Attrition)

head(train_top6)

```

Check the corr for the numeric variables

```{r,  fig.width=12, fig.height=12}
num_train <- train_top6 %>% 
  select_if(~!is.character(.x) & !is.factor(.x))

M <- cor(num_train)
corrplot(M, method="number",col = rainbow(12), tl.cex = 0.4)
```
There is no corr thats greater than abs of 55

```{r,  fig.width=12, fig.height=12}
library(GGally)

ggpairs(train_top6, title = "Pair Plot for Training Set")

```
Down sampling 
```{r}
library(caret)
set.seed(314)
train_top6_ds <- downSample(x = train_top6[, -ncol(train_top6)],
                            y = train_top6$Attrition,
                            yname = "Attrition")

table(train_top6_ds$Attrition)
```
```{r}
colnames(train_top6_ds)
```



select best 3 factors


```{r}

train_top3_ds <- train_top6_ds %>%
  select(JobSatisfaction,WorkLifeBalance,YearsAtCompany,Attrition)

head(train_top3_ds)

```

```{r}

test_top3 <- test %>%
  select(JobSatisfaction,WorkLifeBalance,YearsAtCompany,Attrition)

head(test_top3)

```

now model making knn 

```{r}
set.seed(314)


#  summaryFunction = f1Summary
ctrl <- trainControl(method = "LOOCV")


knn.model <- train(Attrition ~ .,
                   data = train_top3_ds,
                   method = 'knn',
                   trControl = ctrl,
                   tuneGrid = data.frame(k = c(1:100)))

best.knn.model <- knn3(Attrition ~ .,
                       data = train_top3_ds,
                       k = knn.model$bestTune$k)

predictions1 <- predict(best.knn.model, test_top3, type = "class")
cm <- confusionMatrix(predictions1, test_top3$Attrition)
cm
                                        
```

```{r}
knn.model$bestTune$k
```

Naitve Bayes

```{r}
set.seed(314)
library(naivebayes)

#  summaryFunction = f1Summary
ctrl <- trainControl(method = "LOOCV")

#tg <- expand.grid(usekernel =c(T,F),
                  #adjust = seq(0.5,2,by=0.1),
                  #laplace  = c(0,1))


best.nb.model <- train(Attrition ~ .,
                   data = train_top3_ds,
                   method = 'naive_bayes',
                   trControl = ctrl)


predictions2 <- predict(best.nb.model, test_top3, type = "raw")
cm <- confusionMatrix(predictions2, test_top3$Attrition)
cm
```

compair models
```{r}
cm_nb <- confusionMatrix(predictions2, test_top3$Attrition)
cm_knn <- confusionMatrix(predictions1, test_top3$Attrition)

#  accuracy
accuracy_nb <- cm_nb$overall['Accuracy']
accuracy_knn <- cm_knn$overall['Accuracy']

sensitivity_nb <- cm_nb$byClass['Sensitivity']
specificity_nb <- cm_nb$byClass['Specificity']

sensitivity_knn <- cm_knn$byClass['Sensitivity']
specificity_knn <- cm_knn$byClass['Specificity']

#  F1 Score
f1_nb <- (cm_nb$byClass['Precision'] * cm_nb$byClass['Recall']) / (cm_nb$byClass['Precision'] + cm_nb$byClass['Recall']) * 2

f1_knn <- (cm_knn$byClass['Precision'] * cm_knn$byClass['Recall']) / (cm_knn$byClass['Precision'] + cm_knn$byClass['Recall']) * 2

cat("Naive Bayes - Sensitivity:", sensitivity_nb, "Specificity:", specificity_nb, "\n")
cat("KNN - Sensitivity:", sensitivity_knn, "Specificity:", specificity_knn, "\n\n\n\n")

cat("Naive Bayes - Accuracy:", accuracy_nb, "F1 Score:", f1_nb, "\n")
cat("KNN - Accuracy:", accuracy_knn, "F1 Score:", f1_knn, "\n")

```

unlabeled data 

```{r}

class_data <- read.csv("CaseStudy2CompSet No Attrition.csv")
class_data_top3 <- class_data %>%
  select(ID,JobSatisfaction,WorkLifeBalance,YearsAtCompany)

head(class_data_top3)

```
```{r}
row.names(class_data_top3) <- class_data_top3$ID
class_data_top3$ID <- NULL

head(class_data_top3)
```

```{r}

final_predictions <- predict(best.knn.model, class_data_top3, type = "class")
df <- data.frame(ID = rownames(class_data_top3), Attrition = final_predictions )

```

```{r}
write.csv(df, "Case2PredictionsWeaver Attrition.csv", row.names = FALSE)


```

Regression 

```{r}

head(data)
```

```{r}
set.seed(314)

obv <- nrow(data) # number of obervations
shuff_obv <- sample(obv) # shuffled obv index
data_shuff <- data[shuff_obv,] # shuffled data
split <- round(obv*0.80)

train <- data_shuff[1:split,] #  train
test <- data_shuff[(split+1):obv,] # test
```

```{r}
# train
train_top10 <- train%>%
  select(JobLevel,TotalWorkingYears,JobRole,DistanceFromHome,Education,YearsAtCompany,YearsInCurrentRole,PerformanceRating, StockOptionLevel, Age, MonthlyIncome)

head(train_top10)
```
```{r}
str(train_top10)
```


```{r,  fig.width=12, fig.height=12}
num_train <- train_top10 %>% 
  select_if(~!is.character(.x) & !is.factor(.x))

M <- cor(num_train)
corrplot(M, method="number",col = rainbow(12), tl.cex = 0.4)
```
```{r}
# train
train_top7 <- train_top10%>%
  select(JobRole,DistanceFromHome,Education,YearsAtCompany,PerformanceRating, StockOptionLevel, Age, MonthlyIncome)

head(train_top7)
```
```{r,  fig.width=12, fig.height=12}

ggpairs(train_top7, title = "Pair Plot for Training Set")

```
```{r}
train_top3 <- train_top7%>%
  select(JobRole,YearsAtCompany,Age,MonthlyIncome)

head(train_top3)
```
```{r}
test_top3 <- test%>%
  select(JobRole,YearsAtCompany,Age,MonthlyIncome)

head(test_top3)
```


Regression

```{r}
set.seed(314)


ctrl <- trainControl(method = "LOOCV")


best.lm.model <- train(MonthlyIncome ~ .,
                   data = test_top3,
                   method = 'lm',
                   trControl = ctrl)


predictions <- predict(best.lm.model, test_top3[,-4])
```


```{r}
results <- postResample(predictions, test_top3$MonthlyIncome)
results
```
```{r}
summary(best.lm.model$finalModel)
```
```{r}
library(readxl)

reg_data <- read_xlsx("CaseStudy2CompSet No Salary.xlsx")
reg_data_top3 <- class_data %>%
  select(ID,JobRole,YearsAtCompany,Age,MonthlyIncome)

row.names(reg_data_top3) <- reg_data_top3$ID
reg_data_top3$ID <- NULL


final_predictions <- predict(best.lm.model, reg_data_top3)
df <- data.frame(ID = rownames(reg_data_top3), MonthlyI = final_predictions )





```

```{r}
write.csv(df, "Case2PredictionsWeaver Salary.csv", row.names = FALSE)
```

